# Generated by Django 2.1.7 on 2019-02-18 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('student_number', models.IntegerField(default='')),
                ('email', models.EmailField(default='', max_length=254)),
                ('phone_number', models.CharField(default='', max_length=16)),
                ('usage', models.CharField(default='', max_length=100)),
                ('username', models.CharField(default='', max_length=100)),
                ('aggrement', models.BooleanField(default=False)),
                ('pwd', models.CharField(default='', max_length=100)),
                ('apply_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval', models.IntegerField(choices=[(1, 'disapproval'), (2, 'approval')], default=1)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peace.Applicant')),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
