# Generated by Django 2.1.7 on 2019-02-19 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peace', '0002_auto_20190218_0632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='applicant',
        ),
        migrations.AddField(
            model_name='applicant',
            name='permission',
            field=models.IntegerField(choices=[(1, 'disapproval'), (2, 'approval')], default=1),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
