# Generated by Django 2.1.7 on 2019-02-19 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peace', '0003_auto_20190219_0300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='aggrement',
            new_name='agreement',
        ),
    ]
